version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./src:/data
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
